#!/bin/bash
# Minimal xdg-terminal-exec for Lima guests. Arch ARM does not package the real one.
app_id="org.omarchy.terminal"
while (($#)); do
  case $1 in
    --app-id=*)
      app_id=${1#--app-id=}
      shift
      ;;
    --app-id)
      app_id=$2
      shift 2
      ;;
    -e | --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done
exec foot --app-id="$app_id" -e "$@"
